### ISSUE TITLE
Debug Error with Microsoft Visual Studio

### ISSUE THREAD

**Issue by steffeol** [printablealice/a3#7]
Hi

I'm trying to run it as you have mentioned by selecting fem-app or manip-app as the statup app and then using F5. However i get this Debug error with many mismatch warnings. I dint change anything in the code and i build and cmaked it as mentioned in the assignment. Can you help me?

![Annotation 2020-04-13 151701](https://user-images.githubusercontent.com/37240234/79123330-353f5500-7d9a-11ea-9371-6664774a7b25.png)
![Annotation 2020-04-13 151701 2](https://user-images.githubusercontent.com/37240234/79123332-35d7eb80-7d9a-11ea-8a89-d7a4db915523.png)

**Comment by printablealice** [comment]
Hey!

So this is going to be a bit tricky for me to do without being at your computer.

First try adding this as the second line in BernHelpers.h: ```#define EIGEN_DONT_ALIGN```
If that doesn't work also add it to the top of ```fem-app.cpp```
If that doesn't work also comment out all isntances of ```EIGEN_MAKE_ALIGNED_OPERATOR_NEW```

If that didn't work keep reading.

Did you make by double clicking the provided ```runCMake.cmd```?  Please try that instead, and see if it works.  If it doesn't make (says build failed) tell me what the output is (open cmd prompt in that folder, and type runCMake.cmd and press enter, if you just double click the command prompt will disappear.)

If it's still not working keep reading.

- The mismatch warnings are harmless, and not the issue.
- We need more information to debug.  Please paste in the Output from the tab next to Error List.  Please also place the stack trace (click the drop down next to stack frame and take a screen shot).

Otherwise...

See (especially the last section): https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html

If you do get things to work please comment with your solution.

**Comment by steffeol** [comment]
Thanks for the fast response!
The first tip already solved my problem! ("First try adding this as the second line in BernHelpers.h: #define EIGEN_DONT_ALIGN")

Thank you for your time

**Comment by printablealice** [comment]
Dope, thanks for letting me know :)
