### ISSUE TITLE
Updates + Discussion: Questions 10-12

### ISSUE THREAD

**Issue by printablealice** [printablealice/a3#9]
**UPDATE: I made a mistake in where I put the ```if (QUESTION_12) {...}``` block.**

**It should really be inside of evaluate():**

```	
virtual double evaluate(const VectorXd &u) const {
    // Given u, compute O(x(u))
    auto x = get_x(u);
    double O = get_O(x);

    if (QUESTION_12) {
        // TODO: O += ...
    }

    return O;
}
```

**I.e. you are free to make your regularizer a function of ```u``` and/or ```x(u)```.**

**HINT: The best regularizer I've come up with is a function of ```u```.**

**HINT: What if we forget about the physics of the mesh entirely? Is there still something we can say about how the handles should be facing?**

**GENERAL ADVICE**: It may be useful to build your solution from small pieces, instead of trying to get it right all at once.  Just like there's a lot of possible reasons why you could have a black screen in graphics, there are a lot of possible reasons that could explain why your optimizer isn't working the way you expect (or isn't moving at all).  Some ideas:
- What happens if you turn off the main objective, and just minimize your regularizer?--Does it do more or less what you'd expect?
- But before that, how about you try a toy regularizer/objective?
  - For example, if your objective is literally just ```pow(u[5] - .5*PI, 2)```, does the handle snap to where you'd expect?--If not then you have some sort of fundamental issue (could be a bug here or elsewhere, or it could be a conceptual misunderstanding in your head.)

---

If you have specific questions related to questions 10-12 please feel free to post them here as a comment, and to discuss amongst each other.  I will not give you the answer, but I will do my best to explain why your approach does not work.  If you want feedback please include a video of your method running (otherwise I most likely won't be able to tell you what's wrong.)

Some tips:

- There is no one perfect answer, though some regularizers will work much better than others.  Your goal is to find one that at least sort of works.
- You will likely need to play with the weight of your regularizer a bit.  It may be a good idea to add a slider to the GUI so you can do it interactively.
- It is okay if your method is not perfect.
- It is okay if your method is hacky.
- It is okay if your method runs slowly.
  - You can speed things up by using a coarser mesh (```THE_SIM_RUNS_TOO_SLOWLY = true;```)

Best of luck!
-Jim

**Comment by Snokahn** [comment]
![why](https://user-images.githubusercontent.com/50362512/79438977-8c306e80-7fd4-11ea-992a-f73894f8fb54.png)

This happens if I drag the left pin to the right side and vice-versa (aka; when I rotate the bar). Is this "expected" behaviour **before** solving Task 10-12? Note: This is without any regularization and all gradients are ok ("DODu checks") when doing this. 

Additionally, I've noticed that theta_L and theta_R always try to stay close to 0 (and thus also are mostly the same), why?

I am a bit bamboozled as why theta_L and theta_R are the same. The vectors for the handles are drawn such that the left and right one are anti-parallel. However, the drawing method flips the sign of one; so in fact they are parallel. I'm having a hard time understanding the logic behind it; is this related to some local-global coordinate transformation shenanigans?

Lastly, given that the handles behave nonsensical (imo), I would wanna try to regularize the theta values somehow, but we do not have direct access to them. The method where we are supposed to add the regularizer does not get the parameter vector u as input. Do we have to limit ourselves purely to the input vector x?

Can I add the parameter vector u as an input to the method (without breaking the whole code)?

**Comment by nathanael-k** [comment]
1. The expected behavior depends on what you are optimizing. Would the objective value right now get better with the handles turned?
2. theta_L and theta_R being the same is just one way of implementing them. I agree that at first it might seem strange, but this way u can be initialized with 0, which is nice in its own way. I wouldn't call it coordinate transformation, I would just call it the convention used in this program.
3. I really really hope we are allowed to add u to the signature of get_O, wouldn't make sense otherwise. I mean there are ways around it, but the idea of "making the control input part of the objective function as a regularizer" gets used often.

I have one hint I hope is okay to give: Look closely to what the angles are doing in Jim's video tutorial at the end. If you freeze some frames, it should get clear what his regularizer does. There are other options, but its really straight forward with about 5 lines of code.

**Comment by printablealice** [comment]
Thanks Nate! This is a great comment.

3. Yes you can absolutely add u to the signature of get_O!—Or feel free to
stick your regularizer in evaluate() 🙂👍
-Jim

**Comment by printablealice** [comment]
Side note: A standard regularizer (which won’t really help for this
problem) would be something like 1e-3 * .5 * u.squaredNorm().

This essentially says “keep your control small.”  In certain cases it could
also mean “minimum control effort.” This kind of thing is why I’m in the
habit of having u = 0 correspond to the system being at rest. If instead of
being relative position and rotation, u was absolute position in world
space, then the above regularizer would drive the mesh to have both handles
weirdly rotated right on top of each other.  (Though as with everything in
optimization there’s no one right approach and you could use absolute
position and rotation, and rewrite the regularizer as (u -
u_reference).squaredNorm(). At the end of the day it’s mostly just personal
preference.)

**Comment by printablealice** [comment]
Hi guys, I have added an update (and corresponding commit) regarding the regularizer.  Sorry about the confusion and thank you Nate for pointing out the mistake 🙂👍

**Comment by printablealice** [comment]
> Additionally, I've noticed that theta_L and theta_R always try to stay close to 0 (and thus also are mostly the same), why?

This is a great observation.  Another interpretation might be rather that theta_L and theta_R just aren't bothering to move at all (because they don't have to).

> Can I add the parameter vector u as an input to the method (without breaking the whole code)?
Aka: Am I allowed to change double get_O(const VectorXd& x) to double get_O(const VectorXd& u, const VectorXd& x) ?

Yes yes yes, sorry about that.  You can also move the ```if (QUESTION_12) {...}``` block to ```evaluate()``` which is where I meant to put it the first time 🙈

**Comment by nkueng** [comment]
Concerning the regularizer, I would like to share my unsuccessful approach for others to save some time, but also in need of an answer as to why it doesn't work. 

Enjoying the beautiful colors of the tortured beam, I figured "why not regularize the **energies of the triangles at the ends of the beam** such that they relax and adjust their angles instead of storing tons of deformation energy?"

So I did, just to find a disappointing result: Even if **only the energies of the triangles at the ends** are regularized, the optimizer finds solutions where the energies of **all triangles** are relaxed, sacrificing the accuracy of tracking the target position. This, of course, renders my approach useless.

This makes me wonder: Why the heck is the gradient descent incapable of distinguishing between changes to energy due to changing positions of a few nodes vs. all nodes? 
Does it lose track of individual nodes and triangles when computing the neo-Hookean energy? Unfortunately, I lack the mathematical intuition to comprehend what is going on under the hood...

Or maybe something else is going on that is touched on above:

> > Additionally, I've noticed that theta_L and theta_R always try to stay close to 0 (and thus also are mostly the same), why?

>This is a great observation. Another interpretation might be rather that theta_L and theta_R just aren't bothering to move at all.

It seems our gradient descent is just **insensitive to rotations of the handles**! This would explain both the quoted behavior as well as what I am observing: the optimizer does not explore the possibility of rotating the handle in order to decrease the deformation energies at the ends of the beam. Instead, it realizes that stretching the handles does the job of fulfilling the regularized objective, which again relaxes the entire beam instead of only its ends.

**Why is that?**
Where in the process of calculating the gradient `dOdu`do we lose track of changes to `theta_L`and `theta_R`? This is a real mystery to me and I am very thankful for any help with this.

**Comment by nathanael-k** [comment]
I don't think your assumptions are correct.

0. Implement and play around with a constant in front of you regularizer, eg. 10^3 or 10^-3 (have the slider in "log-scale", so setting -3 gives you 0.001). It might work with some sort of scheduling where you change the regularizer over time (I'd recommend by hand to save time).

1. Since the pins are only at the end of the bar, the only way to relax some triangles is to relax all triangles. There is absolutely no possibility to have the triangles at the handles relaxed, while the triangles in the middle are stretched.
Right now you are just penalize stretching, which is not what you want. You'd like to penalize the twist at the handles.
If you'd like to remain with your energy/stretching at the handles approach, a "better" regularizer could be: Don't have configurations where the triangles at the handle are much more stretched than the ones at the middle. Or where you could just compare the two triangles on either side of the handle, they should be stretched roughly the same. No idea if that works.

2. For gradient descent to work, you need a "good" gradient. Think about a rotation of the handle in your first picture: a very small rotation would already give a really bad solution for the actual objective. So in this phase you'd need a pretty strong constant in front of the regularizer to allow the handles to turn. But then later on, this will not allow you to stretch the mesh. There are ways to deal with this. You could try to find the nullspace of your current objective (in the current configuration), finding out in which directions you can change your u without affecting the objective value. And then optimize your secondary objective/regularizer only in this/these directions. This would then give a clear ordering of objective and regularizer. Or you schedule your regularizer. Or you try to find a parametrization that is less sensitive to changes in handle rotation (for example rotating around the objective-vertex instead of the center of the handle).

(yes, I also spent way too much time :) )

**Comment by Snokahn** [comment]
I didn't manage it yet, but thanks for all the input so far, I can't be that far away. I don't have a meaningful approach yet what exactly to compare the thetas to. As soon as my brain decides to stop being stupid, I'll get there (heh).

@nathanael-k Imagine investing that much time into exam preparation, 'M I rite?

**Comment by printablealice** [comment]
> Concerning the regularizer, I would like to share my unsuccessful approach for others to save some time, but also in need of an answer as to why it doesn't work.
> 
> Enjoying the beautiful colors of the tortured beam, I figured "why not regularize the **energies of the triangles at the ends of the beam** such that they relax and adjust their angles instead of storing tons of deformation energy?"
> 
> So I did, just to find a disappointing result: Even if **only the energies of the triangles at the ends** are regularized, the optimizer finds solutions where the energies of **all triangles** are relaxed, sacrificing the accuracy of tracking the target position. This, of course, renders my approach useless.

Cool cool cool!--This is a solid idea.  I'll add just a couple thoughts here (giving away a bit of a possible answer, but I think it's okay).
I was personally able to make regularizing the total energy of the system work, but it's not the greatest.
Some issues you might be having:
- The approach is going to be quite sensitive to the weight you put in front of your sub-objective.  I think something nearer to ```.05``` could work better.
- In addition to being slow to converge, this approach is also slow to compute the gradient if you're using finite differences.  This may give the sense that it's not working (when in reality it's just working really slowly).
  - So make sure you're in Release mode and not Debug mode!
  - And ```THE_SIM_RUNS_TOO_SLOWLY = true;``` will give you a coarser mesh
  - NOTE: In general finite differencing across an optimization tends to be problematic.  Note in this case you're finite differencing across ```E(x(u))``` where ```x(u) = argmin E(x; u)```
    - It was **not** necessary for me to employ the following strategies, but to help with the above issue you could either a) implement the analytic gradient, or b) hack the solver in ```Simulation.h``` to always take a fixed number of steps (I think you could replace the ```1e-6``` with ```0``` to accomplish this).

**Comment by printablealice** [comment]
> Concerning the regularizer, I would like to share my unsuccessful approach for others to save some time, but also in need of an answer as to why it doesn't work.

This was a sweet idea, and I was actually convinced something like it would work (and if you mess around with your weights a bit, and get lucky with the error from finite differences jiggling things around a bit, you may be able to get it to work a bit better).  However I think it suffers from a fundamental problem (essentially 2. from @nathanael-k).  Here is my general idea (definitely not a proof):

_To reduce the energy of the end of the bar by taking it from this shape ```(``` to this shape ```)``` (by rotating the handles), we need to pass through this shape ```|```, which is even higher energy than the first shape!  For nonlinear objectives like the one we have, gradient descent (or even Newton's method) are local methods--i.e. they only understand the effect of making small changes to your optimization variables.  So even though we know that the optimizer should rotate the handle, the optimizer doesn't.  This is because the bars energy landscape is shaped like a W, one local minimum for the first buckling mode, and one local minimum for the other.  And we can't cross that hump in the middle._

A hint for a very different regularizer: What if we forget about the mesh, and energies entirely?  Is there something (very hacky) we can still say about which way the handles should be facing?

**Comment by Snokahn** [comment]
Finally got it (9 lines of code, lol). Thanks yall!

**Comment by vyangETH** [comment]
Hi James, 
You mentioned that in `u` the parameters are given as relative values to the resting state. I was able to get the initial position values (at rest) in global coordinates by using `sim->handleCenters`. Is there a way of getting the initial angle values too?

(Currently I'm just adding PI to get the left and right thetas in one reference frame, but this would not work if we had initialized them with other values...)

**Comment by printablealice** [comment]
> Hi James,
> You mentioned that in `u` the parameters are given as relative values to the resting state. I was able to get the initial position values (at rest) in global coordinates by using `sim->handleCenters`. Is there a way of getting the initial angle values too?
> 
> (Currently I'm just adding PI to get the left and right thetas in one reference frame, but this would not work if we had initialized them with other values...)

Yo!

I am not sure to which initial angle values you are referring, so I will do my best to cover all possible bases.  Please feel free to follow up :)

The nodes don't have any notion of angle.  They are just points in space.  I call the rest position of a given node```s_X```.

To control that node we update the anchor position of its corresponding spring.

Let's assume for example that the node belongs to the the left handle (i.e. it it one of the nodes in the left-most column of the bar) -- see this for video: https://github.com/printablealice/a3/issues/10

The left handle has translation ```x_L, x_R``` and rotation ```theta_L```.  To get the anchor position of the node, we first rotate ```s_X```  by ```theta_L``` about the left handle center (```sim->handleCenters[0]```) and then translate by ```Vector2d(x_L, y_L)```.  For a derivation see: https://github.com/printablealice/a3/issues/5

Rest for the bar (if we neglect gravity) corresponds to ```u = 0```, i.e. all translations and rotations being zero.

**Comment by eastskykang** [comment]
Hi guys! 

I'd like to share my idea. As @nkueng shared here, I was also thinking about adding a regularization term that is proportion to the system energy since I thought desirable solution is a solution not only minimizes IK objective but also system energy. 

But unfortunately it turned out to be not very effective. I think, indeed the desirable solution (handel perpendicular to the bar) is minimizer of the system energy as you can see here (every node is simply blue) but this approach tends to be very easy to stuck to local optima and requires careful tuning. 

![Screenshot from 2020-04-20 14-08-05](https://user-images.githubusercontent.com/3031724/79749994-768eb200-8310-11ea-8cf3-c761e431af52.png)

So, I come up with the idea by using our "prior" knowledge: so the desirable solution is a solution where the targets and handles are lying on the same line. So I penalized the squared distance between a virtual-line which go through the two targets and the handles. 

It seems kinda work, but I found very interesting thing: 
When I optimize this objective, at the beginning it just find a solution something like this. 

![Screenshot from 2020-04-20 14-15-26](https://user-images.githubusercontent.com/3031724/79750601-85299900-8311-11ea-8744-a1fb93782fc1.png)

And then, it very very slowly converged to this:

![Screenshot from 2020-04-20 14-16-36](https://user-images.githubusercontent.com/3031724/79750628-8f4b9780-8311-11ea-90c1-127dc1a87be2.png)

Here, I think we face another problem. The theta in control variable makes non-linearity which makes the whole programming very hard. So maybe one solution to this. is scaling those variables related to the rotation or using different representation of rotation. 

Or we can use another prior knowledge of our, that the theta is better to be perpendicular to the line.
